export const mockUsersProfile = [
  {
    name: 'Kay Park',
    img: 'https://randomuser.me/api/portraits/women/80.jpg',
    location: 'New York',
    description: 'User interface designer and front-end developer',
    skills: [
      'UI / UX',
      'Front End Development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Node',
    ],
    id: 1,
    isPro: true,
  },
  {
    name: 'Moor Branson',
    img: 'https://randomuser.me/api/portraits/men/73.jpg',
    location: 'London',
    description: 'Software Engineer',
    skills: ['Java', 'Spring Boot', 'SQL', 'CI/CD'],
    id: 2,
    isPro: false,
  },
  {
    name: 'Charly Roche',
    img: 'https://randomuser.me/api/portraits/men/0.jpg',
    location: 'Perpignan',
    description: 'Senior Software Engineer',
    skills: ['Go', 'Blockchain', 'SQL', 'CI/CD'],
    id: 3,
    isPro: false,
  },
  {
    name: 'Melinda Ernest',
    img: 'https://randomuser.me/api/portraits/women/37.jpg',
    location: 'Windraak',
    description: 'Software Engineer',
    skills: ['C#', '.net Core', 'NoSQL', 'CI/CD'],
    id: 4,
    isPro: true,
  },
  {
    name: 'Marie Mortensen',
    img: 'https://randomuser.me/api/portraits/women/53.jpg',
    location: 'Bælum',
    description: 'DevOps Engineer',
    skills: ['Docker', 'Kubernetes', 'IT system', 'CI/CD', 'K8s'],
    id: 5,
    isPro: false,
  },
  {
    name: 'Samuel Carmona',
    img: 'https://randomuser.me/api/portraits/men/18.jpg',
    location: 'Pozuelo de Alarcón',
    description: 'Project Manager',
    skills: [
      'Good communication skill',
      'Self-motivation',
      'IT system',
      'marketing',
      'engineering ',
    ],
    id: 6,
    isPro: true,
  },
];
