export const mockUsersProfile = [
  {
    name: 'Kay Park',
    img: 'https://randomuser.me/api/portraits/women/80.jpg',
    location: 'New York',
    description: 'User interface designer and front-end developer',
    skills: [
      'UI / UX',
      'Front End Development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Node',
    ],
    id: 1,
    isPro: true,
    following: [],
    followers: [],
  },
  {
    name: 'Moor Branson',
    img: 'https://randomuser.me/api/portraits/men/73.jpg',
    location: 'London',
    description: 'Software Engineer',
    skills: ['Java', 'Spring Boot', 'SQL', 'CI/CD'],
    id: 2,
    isPro: false,
    following: [],
    followers: [],
  },
  {
    name: 'Charly Roche',
    img: 'https://randomuser.me/api/portraits/men/0.jpg',
    location: 'Perpignan',
    description: 'Senior Software Engineer',
    skills: ['Go', 'Blockchain', 'SQL', 'CI/CD'],
    id: 3,
    isPro: false,
    following: [],
    followers: [],
  },
  {
    name: 'Melinda Ernest',
    img: 'https://randomuser.me/api/portraits/women/37.jpg',
    location: 'Windraak',
    description: 'Software Engineer',
    skills: ['C#', '.net Core', 'NoSQL', 'CI/CD'],
    id: 4,
    isPro: true,
    following: [],
    followers: [],
  },
  {
    name: 'Marie Mortensen',
    img: 'https://randomuser.me/api/portraits/women/53.jpg',
    location: 'Bælum',
    description: 'DevOps Engineer',
    skills: ['Docker', 'Kubernetes', 'IT system', 'CI/CD', 'K8s'],
    id: 5,
    isPro: false,
    following: [],
    followers: [],
  },
  {
    name: 'Samuel Carmona',
    img: 'https://randomuser.me/api/portraits/men/18.jpg',
    location: 'Pozuelo de Alarcón',
    description: 'Project Manager',
    skills: [
      'Good communication skill',
      'Self-motivation',
      'IT system',
      'marketing',
      'engineering ',
    ],
    id: 6,
    isPro: true,
    following: [],
    followers: [],
  },
  {
    name: 'Carine Joly',
    img: 'https://randomuser.me/api/portraits/women/50.jpg',
    location: 'Assens',
    description: 'SRE',
    skills: ['ASP.NET', 'SQL Server', 'CI/CD', 'IIS', 'ORMs '],
    id: 7,
    isPro: true,
    following: [],
    followers: [],
  },
  {
    name: 'Elliot Liu',
    img: 'https://randomuser.me/api/portraits/men/61.jpg',
    location: 'Fauquier',
    description: 'Test Engineer',
    skills: [
      'Selenium',
      'Jira',
      'CI/CD',
      'Chrome Dev Tools',
      'Quality Assurance Software Testing',
    ],
    id: 8,
    isPro: true,
    following: [],
    followers: [],
  },
  {
    name: 'Howard Crawford',
    img: 'https://randomuser.me/api/portraits/men/41.jpg',
    location: 'Queanbeyan',
    description: 'Designer',
    skills: ['Figma', 'UI/UX', 'Graphic Design', 'Photoshop'],
    id: 9,
    isPro: true,
    following: [1, 2, 4, 6, 7],
    followers: [],
  },
];
